version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/myApp/proyecto_Control_de_Cambios/controlador
hooks:
  BeforeInstall:
  ApplicationStop:
    - location: /stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /start_server
      timeout: 900
      runas: root
