#!/bin/bash
rm -f /var/www/html/myApp/proyecto_Control_de_Cambios/controlador/app.py
cd /var/www/html/myApp/proyecto_Control_de_Cambios/controladorNew/
mv app.py /var/www/html/myApp/proyecto_Control_de_Cambios/controlador/
sudo systemctl restart apache2