#!/bin/bash
mkdir /var/www/html/myApp/proyecto_Control_de_Cambios/controlador
cd /var/www/html/myApp/proyecto_Control_de_Cambios/controladorNew/
mv * /var/www/html/myApp/proyecto_Control_de_Cambios/controlador/
sudo systemctl start apache2